language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
# command to run tests
script:
  - pytest --cov
after_success:
  - codecov # submit coverage